### ISSUE TITLE
Build only the 6.2.0 version of GMT

### ISSUE THREAD

**Issue by glennschler** [andrebelem/pythonverse#1]
Thanks for this helpful notebook.

Though this will build the current HEAD of the default branch of GMT. 
Specifically this: `(HEAD -> master, origin/master, origin/HEAD)` which 
is currently a 6.3 pre-release. Possibly unstable as the code changes often
when the maintainers [close pull code requests](https://github.com/GenericMappingTools/gmt/pulls?q=is%3Apr+is%3Aclosed).

In case you want to always work with a stable release, the git clone command
can specify the exact version using the branch/tag option. Plus a clone depth of 
only 1 is quicker, which all that is needed if you have no plans to examine the git
history. For example:
```bash
!git clone --depth 1 --branch 6.2.0 https://github.com/GenericMappingTools/gmt/
```

**Comment by andrebelem** [comment]
Fantastic comment ! thanks for the hint.
